### PR TITLE
refactor(all): deleted the objects package and redone all imports and package declarations

### PR DESCRIPTION
**Pull request by Lordnoname**

### CODE REVIEW

**Comment by DevVersion** [comment]
Sorry, this is not good to merge, because you created the wrong package names.
```src/main``` is only a source folder, not a package.

**Comment by Lordnoname** [comment]
Now there are the right package names.

**Comment by DevVersion** [comment]
Looks good, is this build currently running?

**Comment by Lordnoname** [comment]
Yes it's running pretty well

**Pull request closed without merging**
